### ISSUE TITLE
Huge strings for the toolbar button text break the ui customization page.

### ISSUE THREAD

**Issue by radiculture** [sblask/webextension-skip-redirect#106] opened 2018-10-22 04:46 UTC
I'm running Firefox 62.0.3 on Windows 10. See below.
![skip re](https://user-images.githubusercontent.com/13201612/47278016-66aadc00-d57a-11e8-81f2-71bf05219d7e.PNG)

**Comment by sblask** [comment] 2018-10-22 08:56
This is by design so you can get a quick overview from hovering the toolbar button. Your problem is a side effect, but I won't fix it.

**Closed by sblask** 2018-10-22 08:56 UTC
