### ISSUE TITLE
"Open Link in New Tab" on intermediate link shows notification but does not skip redirect in new tab

### ISSUE THREAD

**Issue by wesinator** [sblask/webextension-skip-redirect#345] opened 2023-03-21 15:45 UTC
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] If you have a problem with a specific website: adding the domain to your no-skip-urls-list does not solve the problem
- [x] The issue is not about adding entries to the default no-skip-urls-list

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [x] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

When opening a link that has an intermediate redirect in a new tab from the browser context menu `Open Link in New Tab`, the extension does not skip the redirect for the new tab, but it shows the notification as if the redirect is skipped. 

Firefox 111 macOS, notifications enabled

**To reproduce:**
 - https://addons.mozilla.org/firefox/addon/skip-redirect/ 
`Support site` link, click it normally, notice the skip redirect and notification

- Open `Support site` link in new tab - notice the skip redirect does not happen, but the notification is sent claiming that it is skipped.

**Comment by sblask** [comment] 2023-03-24 10:14
Duplicate of https://github.com/sblask/webextension-skip-redirect/issues/294

**Closed by sblask** 2023-03-24 10:14 UTC
