### ISSUE TITLE
Infinite redirect loop from links within tumblr posts

### ISSUE THREAD

**Issue by fiddledeedee** [sblask/webextension-skip-redirect#89] opened 2018-04-05 16:56 UTC
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Clicking links within tumblr post descriptions results in the addon looping back to the post itself and never ending up at the target URL. [Example of a post with this issue here.](https://yassmines.tumblr.com/post/169336775742/)

**Comment by hyperfekt** [comment] 2018-04-05 18:17
> - [ ] I checked existing issues (open and closed) for possible duplicates
> - [ ] The issue is not about adding entries to the default blacklist
This is a duplicate of #41, #74, #83 and #87.

**Closed** 2018-04-05 18:36 UTC
