### ISSUE TITLE
https://362b643a66026e.com/afu.php?zoneid=1000715&var=922072   redirection problem

### ISSUE THREAD

**Issue by mozkan007** [sblask/webextension-skip-redirect#98] opened 2018-05-27 10:59 UTC
### What is your browser?

- [x] Chrome  66.0.3359.181 x64

### What is your operating system?

- [x] Windows 10 x64

### Description 

Hi, I have encountered an issue like that. I have blocked  https://362b643a66026e.com/ using Ublock Origin and at the same time I am using your latest Skip redirect extension but this redirection can not be prevented. So this problem occurs on yourporn.sexy website. When I click on a video, this redirection happens. Can you fix it? Thanks.

**Comment by sblask** [comment] 2018-05-31 23:06
Not sure what your problem is, there is no URL encoded in your example URL, so what is Skip Redirect supposed to do? It might be a duplicate of #94 ?

**Closed by sblask** 2018-05-31 23:06 UTC
