### ISSUE TITLE
Redirected to the wrong page

### ISSUE THREAD

**Issue by stordoff** [sblask/webextension-skip-redirect#82] opened 2018-02-20 04:03 UTC
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)
- [x] The issue is not about adding entries to the default blacklist

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Using the example links on https://addons.mozilla.org/en-GB/firefox/addon/neat-url/ , clikcing the first URL: 

https://outgoing.prod.mozaws.net/v1/9b92b9910062e5ab748313bf09ded6984cabce25a1ff2af6eb32f5f5fc3c9787/http%3A//www.phoronix.com/scan.php%3Fpage=news_item&px=Ioquake3-Auto-Updater&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%253A%2BPhoronix%2B%28Phoronix%29

redirects the user to:

https://www.phoronix.com/scan.php?page=news_item&px=Ioquake3-Auto-Updater&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Phoronix+(Phoronix)

(or https://www.phoronix.com/scan.php?page=news_item&px=Ioquake3-Auto-Updater if Neat Url is enabled)

With Skip Redirect enabled, the user is instead sent to: 

https://www.phoronix.com/scan.php?page=news_item

**Comment by sblask** [comment] 2018-02-20 21:23
Duplicate of #71

**Closed by sblask** 2018-02-20 21:23 UTC
